# Generated by Django 4.1.4 on 2022-12-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "managed": True,
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                max_length=13, verbose_name="Уникальный номер книжного издания"
            ),
        ),
        migrations.AlterModelTable(
            name="book",
            table="",
        ),
    ]
